name: komatsu_diagnostic
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.2.11
  cupertino_icons: ^1.0.6
  firebase_core: ^3.3.0
  firebase_app_check: ^0.3.0+4
  # firebase_auth: ^5.1.3
  cloud_firestore: ^5.2.1
  file_picker: ^8.0.6
  firebase_storage: ^12.1.2
  photo_view: ^0.15.0
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/videos/splash.mp4

